### ISSUE TITLE
Add complete support for returning nullable response types

### ISSUE THREAD

**Issue by sufyankhanrao** [apimatic/core-lib-java#99]
In the existing implementation when the response from the API Call is missing and the return type is marked as nullable then the response handler does not return the null value but instead fails by throwing a deserialization exception.

```[tasklist]
### Tasks
- [ ] Add the support for the nullable response type in ResponseHandler class
- [ ] Fix the bug for empty string in `isNullOrWhitespace` utility in CoreHelper class
- [ ] Add unit tests around the changes
```
